### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#1027]
- [x] Drop support for Node 10 (unmaintained), 12 (not maintained from April 2022) and 14 (not maintained in less that a year). Support versions 16 and 18.
- [x] Upgrade all 3p dependencies doing major upgrades (`jwks-rsa`, `redis`, `@aws-sdk/client-s3`, `typescript`, `graphql`, etc). Specify which minimum version of TypeORM is required. Upgrade the peer dependencies.
- [x] Use latest version of AJV and use its TS integration (maybe related: #988).
- [x] Remove the functions `escape` and `escapeProp`. Modern frontend frameworks (React, Angular, Vue, etc) take care of this.
- [x] Improve the interface of the `Context` class to mainly improve type safety.
- [x] Correct the bad design on the precedence of environment variables. (issue: #1021)
- [x] Support optional fields in @ValidateMultipartFormDataBody (issue: #1008)
- [x] Support TypeORM 0.3.0
- [x] Ignore `undefined` values in configuration (issue: #1071)
- [x] Simplify generated CLI files.
- [x] Make the session and JWT systems a bit simpler.

**Comment by kingdun3284** [comment]
Idea: add overloading to support the official json schema type https://www.npmjs.com/package/@types/json-schema for hooks provided by Foalts. According to Open API spec 3.1, it will be a super set of jsonschema.

**Comment by kingdun3284** [comment]
Idea2: Wish to support typescript interface for Configfile with hinted path. For example: 
```
Config.get<P extends FoalsDefaultConfigInterface,K extends string=never>(path:AutoPath<P,K>,...others)
```

**Comment by LoicPoullain** [comment]
Hi @kingdun3284 👋

Version 3 is 10 months late so I decided not to add any new features (except the ones that are already coded) so as to be able to release it after. New features with breaking changes will be studied for the the next major release 👍

**Comment by LoicPoullain** [comment]
The PR has been merged 💪
