### ISSUE TITLE
[V2] Simplify authentication with sessions (summary)

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#799]
# Motivation

Authentication with sessions in Foal is quite complex and requires a lot of code. Current implementation also prevents the framework from adding new features (#525, #521, #510).

In order to follow the framework's philosophy, the session system in version 2 will be simpler (less code) and more intuitive.

# New Features & Breaking Changes

- [x] Allow to specify the store name in a configuration file (#725).
- [x] Simplify the logout (#726).
- [x] Remove the need for a secret (#727).
- [x] Allow to regenerate the session ID (#728).
- [x] Allow to query all sessions of a given user (#510).
- [x] Allow to query all connected users (#778).
- [x] Allow to force the disconnection of a user (#779).
- [x] Remove the need of `setSessionCookie` in login (#796).
- [x] Support flash data (#521).
- [x] Do not update the database schema each time the application is launched (#766).
- [x] Make it super easy/fast to use CSRF tokens with sessions (SPA & regular apps) (#798).
- [x] MongoDB : use an hex ID (#797).
- [x] Cleanup regularly expired sessions (#793).
- [x] Simpler implementation of the session stores (more maintable) (#794).
- [x] Easier to have templates and anonymous users (#795).

**Comment by LoicPoullain** [comment]
Resolved in v2.
