### ISSUE TITLE
Roadmap December-February

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#844]
**This quarter will be mainly devoted to marketing and communication.**

PS: I will be on vacation for a good part of December.

# Main Features

- [ ] Know if the user is authenticated on the client side when using cookies (issue: #843).
- [x] Add `@All` method decorator (issue: #750)
- [x] [AJV] Custom validation errors (issue: #809)

# Marketing / Ecosystem

- [x] Publish a series of articles about what's new in version 2.
- [x] Changing the docs management tool to allow the community to translate them (#776).
- [x] Changing the docs management tool to allow to include future sponsor logos.
- [x] Create a blog (#847).
- [ ] Write articles on the framework's features and publish tutorial videos on Youtube
- [x] Work on a newsletter if people are interested in.
- [x] Improve the website and README contents (#850, #847).

**Comment by anonimusprogramus** [comment]
I haven't had a chance to try v2. 2021 be a good starting year.
