### ISSUE TITLE
Roadmap March-April

### ISSUE THREAD

**Issue by LoicPoullain** [FoalTS/foal#884]
# Features

- [x] Know if the user is authenticated on the client side when using cookies (issue: #843).
- [x] Improve social auth documentation (issues: #581, #754).
- [x] Design Websocket support and start implementing it (issue: #481)
